stages:
  - test
  - build
  - deploy

test-coding-convention:
  image: node:12.19-alpine
  stage: test
  before_script:
    - yarn
  script:
    - yarn test

docker-build-master:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - cp SSH_PRIVATE_KEY_FILE ./id_rsa
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f ./docker/app/Dockerfile.prod -t harbor.zinza.com.vn/medical/chat/socket-server .
    - docker push harbor.zinza.com.vn/medical/chat/socket-server

deploy_app:
  stage: deploy
  image: alpine:latest
  services:
    - docker:dind
  before_script:
    - apk add openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $CI_SSH_SERVER >> ~/.ssh/known_hosts
  script:
    - ssh $CI_SSH_USER@$CI_SSH_SERVER docker-compose -f /home/channam/Desktop/nam/api-socket-server/socket-server/docker-compose.yml down
    - ssh $CI_SSH_USER@$CI_SSH_SERVER docker-compose -f /home/channam/Desktop/nam/api-socket-server/socket-server/docker-compose.yml up -d
