version: '3.4'
services:
  api_socket_server:
    container_name: api_socket_server
    command: yarn dev
    ports:
      - 5000:5000
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile.prod
    volumes:
      - .:/app
    networks:
      - common
    depends_on:
      - zookeeper
      - kafka
      - mongodb
    environment:
      MONGO_URI: 'mongodb://mongodb:27017/Medical'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mongodb:
    container_name: mongodb
    image: mongo:4.2.0-bionic
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - common

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    container_name: zookeeper
    networks:
      - common

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'topic_message,topic_conversation'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: kafka
    networks:
      - common

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data
    environment: 
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - common

  
networks:
  common:
    driver: bridge
