version: '3.4'
services:
  api_socket_server:
    container_name: api_socket_server
    build: .
    command: yarn dev
    ports:
      - 5000:5000
    volumes:
      - .:/app
    networks:
      - common
  mongodb:
    container_name: mongodb
    image: mongo:4.2.0-bionic
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db
    networks:
      - common

  rediscache:
    container_name: rediscache
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data
    networks:
      - common

networks:
  common:
