version: '3.4'
services:
  api_socket_server:
    container_name: api_socket_server
    build: .
    command: yarn dev
    # command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9092 -wait tcp://database:27017 yarn dev"
    ports:
      - 5000:5000
    volumes:
      - .:/app
    networks:
      - common
    depends_on:
      - zookeeper
      - kafka
      - mongodb
    environment:
      REDIS_HOST: 'rediscache'
      REDIS_PORT: '6379'
      REDIS_USER: 'redis_user'
      MONGO_URI: 'mongodb://mongodb:27017/Medical'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mongodb:
    container_name: mongodb
    image: mongo:4.2.0-bionic
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - common

  rediscache:
    container_name: rediscache
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data
    networks:
      - common

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'
    container_name: zookeeper
    networks:
      - common

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - '9092:9092'
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'topic-test:1:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: kafka
    networks:
      - common
    
  consumer:
    build: ../consumer
    container_name: consumer
    # command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9092 -wait tcp://database:27017 yarn dev"
    command: yarn dev
    depends_on:
      - zookeeper
      - kafka
      - mongodb
    environment:
      REDIS_HOST: 'rediscache'
      REDIS_PORT: '6379'
      REDIS_USER: 'redis_user'
      MONGO_URI: 'mongodb://mongodb:27017/Medical'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ../consumer:/app
    networks: 
      - common

networks:
  common:
